project_planning_task:
  description: >
    Analyze the project intake form and create a comprehensive project plan for a complex ERP implementation in healthcare, including:
    1. Detailed scope breakdown with deliverables and phases (ERP modules, integrations, data migration, training, go-live)
    2. Realistic, continuous task breakdown with durations and dependencies (no gaps between phases)
    3. Resource requirements and team composition (roles, FTEs, weeks)
    4. Timeline with milestones and key deliverables
    5. Risk assessment and mitigation strategies (ERP-specific, regulatory, data, change management)
    6. Success criteria and governance structure
    Focus on creating a complete, realistic project plan that can be executed successfully.
  expected_output: >
    A comprehensive JSON object containing detailed project scope, task breakdown with realistic durations (no gaps), resource requirements by role and phase, timeline with milestones, risk assessment, and governance structure. This should be complete enough to serve as the foundation for all project deliverables.
  agent: project_planner_agent

technical_estimation_task:
  description: >
    Review the project plan and provide technical validation for a complex ERP implementation, including:
    1. Technical complexity assessment and effort validation (ERP modules, integrations, data migration)
    2. Resource allocation optimization and skill requirements
    3. Risk identification and technical mitigation strategies (ERP, healthcare compliance)
    4. Timeline validation and technical dependencies (continuous, no gaps)
    5. Prioritization analysis using the provided framework:
       - Score (sum of 5 dimensions: Business Fit, Technology Fit, Value/Savings, Business Readiness, Risk; each 1–5)
       - T-shirt sizing (XS–2XL by score)
       - Priority (P1–P4 by weighted score and business criticality multiplier)
    Ensure all estimates are realistic and technically sound.
  expected_output: >
    A JSON object with validated technical estimates, optimized resource allocation, technical risk assessment, timeline validation (continuous), and prioritization analysis using the provided framework. Include recommendations for technical approach and resource optimization.
  agent: estimation_agent

deliverable_generation_task:
  description: >
    Compile all project information into comprehensive, executive-ready deliverables for a complex ERP implementation:
    1. Detailed Project Charter (executive summary, scope, objectives, project plan with phases, timeline, resources, risks, success criteria, governance)
    2. Mermaid Gantt chart with proper syntax (continuous, no gaps between tasks/phases)
    3. Resource allocation plan with realistic team composition (roles, FTEs, weeks)
    4. Prioritization matrix using the provided framework (score, t-shirt size, priority, business criticality)
    5. Risk assessment and mitigation plan (ERP-specific, regulatory, data, change management)
    Ensure all deliverables are professional, comprehensive, and ready for executive presentation.
  expected_output: >
    Complete project documentation in markdown format including comprehensive charter, properly formatted continuous Mermaid Gantt chart, realistic resource plan, prioritization analysis (using the provided framework), and risk assessment. All deliverables should be executive-ready and comprehensive enough for project execution and online publication.
  agent: deliverable_agent